name: 'Setup Go Environment'
description: 'Set up Go with caching and dependency verification'
inputs:
  go-version:
    description: 'Go version to use'
    required: false
    default: '1.25'

runs:
  using: 'composite'
  steps:
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ inputs.go-version }}
        cache: true

    - name: Download dependencies
      shell: bash
      run: go mod download

    - name: Verify dependencies
      shell: bash
      run: go mod verify
